# 存储设定
data-option:
  # 存储类型, 支持: MySQL, SQLite, YAML
  type: YAML
  # MySQL url, 例如 jdbc:mysql://127.0.0.1/minecraft 格式: jdbc:mysql://MySQL地址/数据库名
  url: jdbc:mysql://localhost/minecraft?useSSL=false
  # 数据库用户名
  user: "root"
  # 数据库密码
  password: "root"
# 如果未填写市场名的话, 默认操作市场
default-market: "example"
# 是否启用命令短写帮助
command-help: true
# 市场状态文本
status-text:
  loaded: "&a已加载"
  error: "&c出现异常"
  no-permission: "&c无权使用"