name: ServerMarket
main: com.blank038.servermarket.ServerMarket
authors:
  - Blank038
depend:
  - AyCore
softdepend:
  - Vault
  - PlayerPoints
  - NyEconomy
version: ${version}
api-version: 1.13
commands:
  servermarket:
    aliases:
      - market
      - sale
    description: Command for ServerMarket.