# 支持: zh_CN, en_US, es_ES, fr_FR, ko_KR, ru_RU, tr_TR
language: "zh_CN"
# 存储设定
data-option:
  # 存储类型, 支持: MySQL, YAML
  type: YAML
  # MySQL url, 例如 jdbc:mysql://127.0.0.1/minecraft 格式: jdbc:mysql://MySQL地址/数据库名
  url: jdbc:mysql://localhost/minecraft?useSSL=false
  # 数据库用户名
  user: "root"
  # 数据库密码
  password: "root"
  # 数据库读取超时打开数据锁时长, 2 = 1秒
  time-out: 120
  # 同步提示
  pull-notify: true
# 如果未填写市场名的话, 默认操作市场
default-market: "example"
# 是否启用命令短写帮助
command-help: true
# 通用参数设定
settings:
  # 玩家离线交易检测间隔, 单位: 秒
  offline-transaction-interval: 60
# 冷却设定, 单位: 秒
cooldown:
  action: 3
# 税收流向账户, 参数类型: UUID
tax-account: "UUID"
# 跨服通知设定
notify-option:
  # 使用模式, 目前支持: self/MySQL, 未来会提供对 PostgreSQL/Redis 的支持
  use: self
  # 使用不同模式请配置对应参数
  type:
    self:
      host: localhost
      listen: 54211
    mysql:
      url: jdbc:mysql://localhost/minecraft?useSSL=false
      user: root
      password: root
      prefix: "servermarket_"
    postgresql: { }
    redis: { }